module.exports = {
  FIREBASE_API_KEY: 'test-api-key',
  FIREBASE_AUTH_DOMAIN: 'test.firebaseapp.com',
  FIREBASE_DATABASE_URL: 'https://test-default-rtdb.firebaseio.com',
  FIREBASE_PROJECT_ID: 'test-project',
  FIREBASE_STORAGE_BUCKET: 'test.appspot.com',
  FIREBASE_MESSAGING_SENDER_ID: '000000000000',
  FIREBASE_APP_ID: '1:000000000000:web:000000000000',
  FIREBASE_MEASUREMENT_ID: 'G-TEST000000',
  SPOTIFY_CLIENT_ID: 'test-client-id',
  SPOTIFY_REDIRECT_URI: 'spotifyjamsesh://callback',
  CLOUDINARY_CLOUD_NAME: 'test-cloud',
  CLOUDINARY_UPLOAD_PRESET: 'test-preset',
  CUSTOM_TOKEN_URL: 'https://test-worker.workers.dev',
};
